name: markdown_notes
description: A simple, powerful Markdown notes app built with Flutter.
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_markdown: ^0.7.3
  path_provider: ^2.1.5
  uuid: ^4.4.0
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  file_picker: ^10.2.0
  provider: ^6.1.5
  go_router: ^15.1.1
  flutter_localization: ^0.3.2
  logger: ^2.5.0
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  logging: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true
